### ISSUE TITLE
Jumps to the definition of the type of the symbol under the cursor fail

### ISSUE THREAD

**Issue by tceioos47** [Hoffs/omnisharp-extended-lsp.nvim#26]
Jumps to the definition of the type of the symbol defined by user is OK,
but fails for that defined in third-party or .net bulit-in assemble.
Error hint below:
![image](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/140125235/b8f1baa5-f447-4291-a4e5-9b35fec14c99)

**Comment by Hoffs** [comment]
Hi, could you include output of LSP log (can be opened with `:LspLog`) and maybe a snippet of solution where you are getting this? And your config possibly.

**Comment by Hoffs** [comment]
closing the issue, if you're still having issues with latest version, please reopen this issue or create a new one

**Comment by tcrundall** [comment]
I think there's been a misunderstanding.

So far as I can tell, omnisharp-extended-lsp doesn't provide any support for `lsp_type_definitions`.

I myself was stuck on this for a while, before I realised that my "go to definition of type of symbol" was mapped to telescope: `require("telescope.builtin").lsp_type_definitions`, while "go to definition of symbol" was mapped to omnisharp-extended-lsp: `require("omnisharp_extended").lsp_definition`.

And so, the reason why `lsp_type_definitions` fails for third party libraries, is because telescope doesn't do any decompilation.

Funnily enough, if you first fine the type spelled out somewhere, you can get omnisharp-extended-lsp to decompile it for you with `lsp_definition`, and then for the remainder of your nvim session you can use telescope's `lsp_type_definitions` to jump to that decompiled file.

Happy to provide a minimal init.lua and example csharp file and a log, but if I've understood the problem it seems overkill atm.

It would be cool if omnisharp-extended-lsp would implement `lsp_type_definitions` though!
