### ISSUE TITLE
Go to definition fails after doing :LspRestart

### ISSUE THREAD

**Issue by svermeulen** [Hoffs/omnisharp-extended-lsp.nvim#28]
I have found that I can go to a third party dll class/method definition just fine, but if I run `:LspRestart` and then attempt to do that same thing again, I get this error:

![image](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/810762/08f38a0e-044a-49d1-b0af-997ff1595361)

BUT - this issue goes away completely if I uncomment [this line](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/blob/main/lua/omnisharp_extended.lua#L166) and then comment out the line after that.  I assume there's a reason we don't want to uncomment this though

**Comment by Hoffs** [comment]
Hi,

So my guess is that after the restart LSP client is no longer attached to the buffer (`:LspInfo` shows this). The plugin [manually attaches the client](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/blob/main/lua/omnisharp_extended.lua#L61) when creating these buffers as they are not real files, so automatic detection doesn't work (afaik).

But I can't really reproduce this, since LSP is not attached none of the commands seem to work for me. My steps were:
- go to definition on `Console.WriteLine` (User code buffer)
- perform `:LspRestart` (Assembly code buffer)
- go to definition on `UnsupportedOSPlatform` attribute (Assembly code buffer)

Could you provide more details of exact steps you're performing (movements, which "go to definition" command)?

**Comment by svermeulen** [comment]
Ok so after reproducing it a bunch more time I've noticed the following:
* Is not related to `:LspRestart`.  I can repro without this step
* Once the issue does get hit, I get it every time I attempt to run `:lua vim.lsp.buf.definition()` on the same value (and also I think other values too).  Even `:LspRestart` at this point does not help.  Issue persists until complete vim restart

Some examples of how I repro'd it:
* Open neovim.  Open Program.cs:

```
using System;

public class Program
{
    static void Main()
    {
        Console.WriteLine("hello");
        Console.WriteLine("Press any key to exit...");

        Console.ReadKey();

        var result = new StringBuilder();
    }
}
```

* Go to StringBuilder above.  Execute `:lua vim.lsp.buf.definition()`.  Move around, maybe other buffers.  Go to `Console` Execute `:lua vim.lsp.buf.definition()`.  Issue occurs.   I was able to repro it doing it this way after full restart maybe half the time.

Environment:  Windows. neovim 0.9.4

**Comment by svermeulen** [comment]
I think it might be related to current directory.  I can force this to happen every time by running go-to-def on a dll, then running `:cd <something>`, then trying go-to-def again on same dll.  So maybe a windows path related thing.

I noticed also that when it does work, the buffer name includes current directory

**Comment by Hoffs** [comment]
> I think it might be related to current directory. I can force this to happen every time by running go-to-def on a dll, then running `:cd <something>`, then trying go-to-def again on same dll. So maybe a windows path related thing.

Hmm, interesting. I can reproduce this on windows, but not on unix.

This is mostly likely related to windows paths, since they are [handled quite inconsistently](https://github.com/neovim/neovim/issues/23006). What probably happens, since current directory is changed, path like `file:///$metadata$/Project/TextDocReferenceRepro/Assembly/System/Console/Symbol/System/Console.cs` gets expanded relative to new current directory and it can't find matching buffer. The other function has more manual logic and manages to find appropriate buffer instead of relying on native neovim implementation.

I'll keep this in mind once I get around to [finishing the refactoring](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/pull/19).

As for now, is this a specific workflow where current directory is changed frequently?

**Comment by Hoffs** [comment]
With latest update this no longer seems to be an issue, when modifying current directory, please reopen if you're still experiencing this
