### ISSUE TITLE
Options for how to manage buffers

### ISSUE THREAD

**Issue by MikaelElkiaer** [Hoffs/omnisharp-extended-lsp.nvim#3]
Hi, it's me again.

It might be that this lies without the scope of this extension, but here goes.

I'd like to handle buffers a bit differently:
1. Close "definition buffers" once they lose focus.
2. Keep subsequent definitions in the same buffer.

And possibly related to this, I've noticed that if I go to a definition I can close that buffer without issue.
However, the second time I go to the same definiton, the buffer is marked as edited - so that it asks me if I want to save before closing it.

All of this could also be me who is still confused about buffers in vim, and the fact that I am using some plugins I've yet to understand  (thanks to [nvchad/nvchad](https://github.com/NvChad/NvChad)).

**Comment by Hoffs** [comment]
9c76674be87e92b0090417359b063fe130d9c158 should fix buffers getting marked as modified.

Regarding 1 and 2, both of those break the usual work flow of vim, since most new file opening actions create new buffers in vim, so these should stay similar. 
Furthermore it would break jump list functionality, so if you go 3 levels deep and want to jump back 2, you no longer can since those ephemeral buffers no longer exist. So if you go down one path and then you realize that you want to check other path now you gotta start from your real buffer all the way down.
And in general sometimes you want to have 2 different metadata buffers loaded to check between, maybe even as splits. A single buffer doesn't sound great.

I was thinking of adding a single command to close all metadata buffers but with the readonly change they shouldnt be getting in the way anymore.

**Comment by MikaelElkiaer** [comment]
Thanks for the fix. And thanks for clarifying - it's a complicated eco system, so it's hard to know for newbies what is complex to so and what is not. :)

Sounds good with a shortcut for closing all metadata buffers though. ;)
