### ISSUE TITLE
Go to implemenation returns empty QuickFixes for .NET build-ins.

### ISSUE THREAD

**Issue by marcinjahn** [Hoffs/omnisharp-extended-lsp.nvim#38]
I've enabled the implementations handler to go via omnisharp-extended. The omnisharp server always returns an empty list of quickfixes. I added some logs to the plugin to see what the response is:

![image](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/10273406/ecdccf75-0bc7-45cc-98c7-868c361b2224)

The first two logs are mine, the last one ("No locations found") is already built into the plugin.

Any idea why it doesn't work? The implementations do show up for types that I've defined in my program by myself. Only external code (like `System.Console.WriteLine` does not work). I did include this in my omnisharp.json:

```json
{
  "RoslynExtensionsOptions": {
    "enableDecompilationSupport": true
  }
}
```

although, it seems that this setting is the default so probably it's not needed anyway.

**Comment by marcinjahn** [comment]
Alright, I just realized that Omnisharp isn't capable yet to show .NET code implementation: https://github.com/dotnet/vscode-csharp/issues/6784

Then, I wonder, what is the actual issue that this plugin solves? Could someone give some concrete example of a situation where this plugin is useful?

**Comment by Hoffs** [comment]
Hello,
In omnisharp-roslyn, decompilation support enables GotoDefinition and GotoTypeDefinition commands to navigate to decompiled source code, but since those documents are not actual files, a standard LSP will fail by trying to open returned non-existent file path. This plugin handles that and creates buffers with source which enables proper navigation to them. From the issue you linked, .NET SDK is not supported that well, function implementations will be shown as empty, but otherwise it mostly returns correct file. Anything besides .NET SDK surface, should work perfectly fine.

Furthermore, source generation introduced another type of non-existent document, so in similar fashion as with metadata documents, this plugin also enables various LSP commands (including the implementation one) to properly navigate to source generated files.

**Comment by marcinjahn** [comment]
Alright, so the plugin allows to see:
- source code of nuget packages
- Source generated files

and, when omnisharps starts to support it, .NET SDK code should also automatically start to be browsable

That’s great, thanks for the explanation.
