### ISSUE TITLE
Thoughts on not attaching the lsp client to the assembly/decompiled buffer?

### ISSUE THREAD

**Issue by hoelter** [Hoffs/omnisharp-extended-lsp.nvim#7]
First off, thanks for creating this! I just came across your plugin and it solves a definite pain point I've had when using neovim on .net code bases.

After some quick testing of this plugin I noticed that the lsp client seems to be executing on the assembly files and puts a bunch of diagnostic errors into them if I navigate to and away from them in quick succession. Removing this line `vim.lsp.buf_attach_client(bufnr, client_id)` inside the `buf_from_metadata` method seems to stop it from happening.

For the majority of use cases that I would have, I would not want the lsp client to try and execute on the assembly/decompiled buffer. I'm assuming your use cases may differ, but I bring this up because I noticed some question marks above the line attaching the lsp client. What are your thoughts on this?

**Comment by Hoffs** [comment]
I am not 100% now, since it's been a while since I worked on this, but if the buffer is not attached to LSP client, then no LSP commands will work. To begin with, it uses clients that are attached to current buffer at the start of `lsp_definitions`. Then, if I am not mistaken, the file is loaded using LSP protocol to the LSP server, so when any command is executed in the file at certain position, LSP server has to have this file loaded. So for metadata files this maybe could be circumvented, by explicitly going with `'o#/v2/gotodefinition` call, instead of regular LSP `textDocument/definition`.

So overall, I believe it is not as simple as not attaching the client to the buffer, as that breaks definition lookup from inside metadata files. It maybe could be worked around by using custom command and not lsp handler, but at this moment I haven't felt that current behavior causes me issues, so I don't feel like spending time on this.

**Comment by hoelter** [comment]
I appreciate your thoughts on this. I haven't felt a need for definition lookups inside the metadata file since disabling LSP on them, but if I change my mind and spend time on getting it working like you're suggesting I'll submit a PR. Thanks again for creating this plugin and putting it out into the world!
